# B4本読み第４回 
## 基底と部分空間<br>
 テスト担当：大畑 昌輝，実装担当：伊藤 秀真

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- 第4回の4だけ全角になってる
- 細かいけど，「B4 本読み第 4 回」という風に，全角と半角の間は半角スペースを入れよう

# 目次
- jupyter notebook
- 目的
- 環境
- 実装課題
- 線形独立と線形従属
- $A\in{\mathbb{C}^{M \times 1}}$ が$M\times N$行列の列空間に含まれるか判定する<br>関数の仕様・テスト
- $M\times N$ の行列の列ベクトルが線型独立かどうか判定する<br>関数の仕様・テスト
- まとめ

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- 一部粒度が怪しい\
    線形独立と線形従属まではいいとして，その下の2つ（A∈C^(M×1)が...，とM×Nの...）は課題の内容．\
    なので，上記2項目の代わりに，関数の仕様とテスト結果，みたいな項目を書いておくのがよいかと．\
    ちなみに，目次に書いてないものを各スライドのタイトルに採用しても問題ない．
- 目次では「環境」スライドでは「テスト環境」と書いているけど，何か使い分けがある？

# jupyter notebook
- コード，およびデータ用のWebベース対話型開発環境
- 対応している言語はPythonの他にも40種類以上
- アドオンを使うことでスライドを作ることもできる．


### <font color="DarkOrange"> 上のセルに対するコメント</font>
-  RISEというアドオン，とか書いておいた方が親切かもね
- コードおよびデータ用のWebベース対話型開発環境...？と思って調べたんだけど，\
   https://jupyter.org/ こっから引っ張ってきてる？ \
   多分この説明，JupyterLabの説明を日本語訳しちゃってる気がする．\
   Jupyter notebook の説明はその下にあるので念のため確認しておくれ

# 目的
- 基底，部分空間を理解する．
- $N$ 次元空間における線形独立と線形従属について理解する．
- ランクと線形独立との関係性について理解する．
- 指定された実装課題を様々なパターンでテストする．

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- 基底，部分空間についての説明がない．\
  「基底，部分空間を理解する」という項目と，「線形独立と線形従属について理解する」という項目があるけど，\
   説明があるのは線形独立・線形従属の方だけ．\
   ランクと線形独立との関係性は，関数の説明のところで使われているけど，これも説明っぽい説明がない．\
   説明用のスライドがあった方が良いかもしれない
- 「N次元空間における」という前置きなくてもいいんじゃないかなぁ    

# テスト環境
- OS:Windows10 Home
- コードの開発環境:jupyter notebook(Python3.7.4)

# 実装課題
- $M\times 1$ 列ベクトルが，$M\times N$ 行列の列空間に含まれるか判定する関数を実装
- $M\times N$ の行列の列ベクトルが線型独立かどうか判定する関数を実装

## 線形独立と線形従属
ベクトル空間 $V$ の $N$ 個の要素 $u_1,u_2,\dots,u_N\in{V}$，<br>スカラ $c_i,i=1,\dots,N$ に対して，<br><br>
$c_1u_1+c_2u_2+\dots+c_Nu_N= 0$ <br><br>
となる必要十分条件が $c_1=c_2=\dots c_N=0$ であるとき，$u_1,u_2,\dots,u_N$ は線形独立といい，そうでない場合は一次従属であると言う．
    

## 1. $A\in{\mathbb{C}^{M \times 1}}$ が$M\times N$行列の列空間に含まれるか判定する関数の仕様①

- ランク $\Longleftrightarrow$ 線形独立な列ベクトル又は行ベクトルの最大本数
- $M\times 1$ が$M\times N$ 行列の列空間に含まれる $\Longleftrightarrow$ $M \times N$行列の線形独立な<br>列ベクトルが$A$の 0 でない要素以上有る
<br>
以上の2点から，$M\times N$行列を$B$ とすると $Rank(B)\ge A$の非零の要素数　<br>の時，行列$A$ は$M\times N$ の列空間には含まれる．



### <font color="DarkOrange"> 上のセルに対するコメント</font>
- 2個目がなんか怪しい \
  $M\times 1$ が$M\times N$ 行列の列空間に含まれる $\Longleftrightarrow$ $M \times N$行列の線形独立な列ベクトルが$A$の 0 でない要素以上有る 
  - 最初の部分は「$A$ が$M\times N$ 行列の列空間に含まれる」とした方がいいかも．「$M\times 1$」だけでは意味が通らない．
  - 「$M \times N$行列の線形独立な列ベクトル」は「$M \times N$行列の線形独立な列ベクトルの個数」とし，\
      「$A$の 0 でない要素」は「$A$の 0 でない要素の数」とした方がより意味が明確になると思う．
  - 以上有る，というので間違いではないと思うけど，もういっそ「...列ベクトルの個数≧...要素の数」とした方がわかりやすいと個人的には思う．
- 最後の部分，列空間「には」というのはどういう意味だろうか．特に何もなければ，「列空間に」でいいと思う．

## 1. $A\in{\mathbb{C}^{M \times 1}}$ が$M\times N$行列の列空間に含まれるか判定する関数の仕様②
### 実装手順
- 与えられた$M\times N$行列の行基本変形を繰り返し，階段行列を作る．
- 階段行列のすべて 0 でない行の数をカウントし，ランクを求める．
- そのランクが$A$ の非零の要素数よりも大きい場合，True を返し，それ以外は False を返す．

### <font color="DarkOrange"> 上のセルに対するコメント</font>
1点だけ．\
3つ目の項目：そのランクが$A$ の非零の要素数よりも「大きい」場合，True を返し，それ以外は False を返す．\
とあるけど，仕様上「非零の要素数と同じ」場合にもTrueにならないとまずいはず．

## 1.1 列空間に含まれる場合①
- $M=N=3$の正方行列<br>
以降，$\mathbb{C}^{M \times 1}$に属する行列を$A$，$M\times N$行列を $B$とします．<br>
$A=\left(\begin{array}{cc} 1 \\ 1 \\ -3 \\ \end{array} \right) ,B= \left(\begin{array}{cc} 1 & 1 & -3 \\ -1 & 3 & 5 \\ 0 & 3 & 6 \\ \end{array} \right)$<br><br>$　\Longleftrightarrow　rank(B)=$$A$ の非零の要素数=3
<br><br>
予期される出力はTrue

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- タイトルからスライドの内容が把握できない．以下の要素をいれたタイトルにしてほしい．
  - このスライドでは，テストした例を示すということ
  - 他の例との差別化（正方行列であるということ，出力結果はTrueとなること）
  - 例: テストケース1（正方行列，列空間に含まれる場合）
- スライド中に1項目しかないので箇条書きの・はない方が無難．
- $B$とします→$B$とする
- ↔︎の記号は同値を意味するのでここでは使えないはず．「$rank(B)=A$ の非零の要素数=3 であるならば$A=...B=...$」成り立たない．

In [0]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1],[1],[-3]])
        B=np.array([[1,1,-3],[-1,3,5],[0,3,6]],dtype="float64")
        actual = column_space(A,B,1)
        self.assertTrue(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.

[[ 1.  1. -3.]
 [ 0.  4.  2.]
 [ 0.  3.  6.]]
→
[[ 1.  1. -3.]
 [ 0.  4.  2.]
 [ 0.  3.  6.]]
→
[[ 1.   1.  -3. ]
 [ 0.   4.   2. ]
 [ 0.   0.   4.5]]
→



----------------------------------------------------------------------
Ran 1 test in 0.004s

OK


## 1.1 列空間に含まれる場合②
- $M=3，N=4$の行列<br>
<br>
$A=\left(\begin{array}{cc} 0 \\ 1 \\ 0 \\ \end{array} \right) ,B= \left(\begin{array}{cc} 1 & 2 & -3 & 5 \\ 0 & 3 & -3 & 8 \\ 2 & 4 & -6 & 10 \\ \end{array} \right)$　<br><br>　$\Longleftrightarrow　　rank(B)=2 \ge$$A$ の非零の要素数=1
<br><br>
予期される出力は True

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- タイトルの修正（上と同様）
- ↔︎の修正
- ・はない方が無難

In [0]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[0],[1],[0]])
        B=np.array([[1,2,-3,5],[0,3,-3,8],[2,4,-6,10]],dtype="float64")
        actual = column_space(A,B,1)
        self.assertTrue(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.

[[ 1.  2. -3.  5.]
 [ 0.  3. -3.  8.]
 [ 2.  4. -6. 10.]]
→
[[ 1.  2. -3.  5.]
 [ 0.  3. -3.  8.]
 [ 0.  0.  0.  0.]]
→
[[ 1.  2. -3.  5.]
 [ 0.  3. -3.  8.]
 [ 0.  0.  0.  0.]]
→



----------------------------------------------------------------------
Ran 1 test in 0.004s

OK


## 1.1 列空間に含まれる場合③
- $3\times 2$，$3\times 3$，$3\times 4$ の場合において float 型，Complex 型についても調べた．
- $4\times 3$，$4\times 4$，$4\times 5$ の場合についても同様に調べた．

$\Rightarrow$ すべてのパターンにおいて結果が一致した．

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- タイトルの修正
- floatは全部小文字なのにComplexは大文字スタートなのは，Complexは自作のクラスだから？\
  意味を持たせているならスルーでOK

## 1.2 列空間に含まれない場合①
- $M=N=3$ の正方行列<br>
<br>
$A=\left(\begin{array}{cc} 1 \\ 1 \\ -3 \\ \end{array} \right) ,B= \left(\begin{array}{cc} 1 & 1 & -3 \\ -1 & 3 & 5 \\ 3 & 3 & -9 \\ \end{array} \right) $<br><br>$　\Longleftrightarrow　rank(B)=2 <$$A$ の非零の要素数=3
<br><br>
予期される出力は False

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- タイトルの修正
- ↔︎の修正
- ・はない方が無難

In [0]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1],[1],[-3]])
        B=np.array([[1,1,-3],[-1,3,5],[3,3,-9]],dtype="float64")
        actual = column_space(A,B,1)
        self.assertFalse(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.

[[ 1.  1. -3.]
 [ 0.  4.  2.]
 [ 3.  3. -9.]]
→
[[ 1.  1. -3.]
 [ 0.  4.  2.]
 [ 0.  0.  0.]]
→
[[ 1.  1. -3.]
 [ 0.  4.  2.]
 [ 0.  0.  0.]]
→



----------------------------------------------------------------------
Ran 1 test in 0.004s

OK


## 1.2 列空間に含まれない場合②
- $M=4，N=3$の行列<br>
<br>
$A=\left(\begin{array}{cc} 1 \\ 1 \\ -3 \\ 2 \\\end{array} \right) ,B= \left(\begin{array}{cc} 1 & 1 & -3 \\ -1 & 3 & 5\\ 5 & 7 & -3 \\ 3 & 3 & -9 \\ \end{array} \right)$<br><br>$　\Longleftrightarrow　rank(B)=3 <$$A$ の非零の要素数=4
<br><br>
予期される出力はFalse

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- タイトルの修正
- ↔︎の修正
- ・はない方が無難

In [0]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1],[1],[-3],[2]])
        B=np.array([[1,1,-3],[-1,3,5],[5,7,-3],[3,3,-9]],dtype="float64")
        actual = column_space(A,B)
        self.assertFalse(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK


## 1.2 列空間に含まれない場合③
- $3\times 2$，$3\times 3$，$3\times 4$の場合においてfloat型，Complex型についても調べた．
- $4\times 3$, $4\times 4$，$4\times 5$の場合についても同様に調べた．

$\Rightarrow$ すべてのパターンにおいて結果が一致した．

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- タイトルの修正
- floatは全部小文字なのにComplexは大文字スタートなのは，Complexは自作のクラスだから？\
  意味を持たせているならスルーでOK

## 2.$M\times N$ の行列の列ベクトルが線型独立かどうか判定する関数の仕様
ランクは 1 次独立な列ベクトルの最大本数であるため，
$A\in{\mathbb{C}^{M \times N}}$ について，$Rank(A)=N$ であるとき，$A$の列ベクトルは線形独立である．
<br>
### 実装手順
- 入力行列の行数と列数をチェックし，$M<N$の時ランクが$N$にならないためFalseを返す．
- 与えられた行列の行基本変形を繰り返し，階段行列を作る．
- 階段行列のすべて0でない行の数をカウントし，ランクを求める．
- $Rank(A)=N$の場合はTrueを返す．一致しない場合はFalseを返す．

### <font color="DarkOrange"> 上のセルに対するコメント</font>
$A$の列ベクトルは「全て」線形独立であるの方が正確じゃないかな\
各列ベクトルそれぞれに対して線形独立かどうかは判定可能だし．

## 2.1 $M\times N$行列の列ベクトルが線形独立の場合①
- $M=N=3$の正方行列<br>
$\left(\begin{array}{cc} 1 & 1 & -3 \\ -1 & 3 & 5 \\ 0 & 3 & 6\\ \end{array} \right) \to \left(\begin{array}{cc} 1 & 1 & -3 \\ 0 & 2 & 1 \\ 0 & 0 & \frac{9}{2} \\ \end{array} \right) $<br>$\Longleftrightarrow rank=N=3 \Longleftrightarrow $線形独立 <br>
<br>
予期される出力はTrue

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- タイトルの修正
- ↔︎の修正
- ・はない方が無難

In [0]:
import linearly_check as lc

class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1,1,-3],[-1,3,5],[0,3,6]],dtype="float64")
        #expected = True
        actual = linearly_independent(A)
        self.assertTrue(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.

[[ 1.  1. -3.]
 [-1.  3.  5.]
 [ 0.  3.  6.]]
→
[[ 1.  1. -3.]
 [ 0.  4.  2.]
 [ 0.  3.  6.]]
→
[[ 1.  1. -3.]
 [ 0.  4.  2.]
 [ 0.  3.  6.]]
→
[[ 1.   1.  -3. ]
 [ 0.   4.   2. ]
 [ 0.   0.   4.5]]
→



----------------------------------------------------------------------
Ran 1 test in 0.008s

OK


## 2.1 $M\times N$行列の列ベクトルが線形独立の場合②
- $M>N$の行列<br>
$\left(\begin{array}{cc} 1 & 1 \\ -1 & 3 \\ 0 & 3 \\ \end{array} \right) \to \left(\begin{array}{cc} 1 & 1 \\ 0 & 4 \\ 0 & 0 \\ \end{array} \right) $<br>$\Longleftrightarrow rank=N=2 \Longleftrightarrow $線形独立 <br>
<br>
予期される出力はTrue

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- タイトルの修正
- ↔︎の修正
- ・はない方が無難

In [0]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1,1],[-1,3],[0,3]],dtype="float64")
        #expected = True
        actual = linearly_independent(A)
        self.assertTrue(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

## 2.1 $M\times N$行列の列ベクトルが線形独立の場合③
- $3\times 3$，$3\times 2$の場合においてfloat型，Complex型についても調べた．
- $2\times 2$，$4\times 3$についても同様に調べた．

$\Rightarrow$ すべてのパターンにおいて結果が一致した．

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- タイトルの修正
- floatは全部小文字なのにComplexは大文字スタートなのは，Complexは自作のクラスだから？\
  意味を持たせているならスルーでOK

## 2.2 $M\times N$行列の列ベクトルが線形従属の場合①
- $M=N$の正方行列<br>
$\left(\begin{array}{cc} 1 & 1 & -3 \\ -1 & 0 & 5 \\ 0 & 3 & 6\\ \end{array} \right) \to \left(\begin{array}{cc} 1 & 1 & -3 \\ 0 & 1 & 2 \\ 0 & 0 & 0\\ \end{array} \right) $<br>$\Longleftrightarrow rank=2\neq N \Longleftrightarrow $線形従属<br>
<br>
予期される出力はTrue

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- タイトルの修正
- ↔︎の修正
- ・はない方が無難

In [0]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1,1,-3],[-1,0,5],[0,3,6]],dtype="float64")
        actual = linearly_independent(A)
        self.assertFalse(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.

[[ 1.  1. -3.]
 [-1.  0.  5.]
 [ 0.  3.  6.]]
→
[[ 1.  1. -3.]
 [ 0.  1.  2.]
 [ 0.  3.  6.]]
→
[[ 1.  1. -3.]
 [ 0.  1.  2.]
 [ 0.  3.  6.]]
→
[[ 1.  1. -3.]
 [ 0.  1.  2.]
 [ 0.  0.  0.]]
→



----------------------------------------------------------------------
Ran 1 test in 0.004s

OK


## 2.2 $M\times N$行列の列ベクトルが線形従属の場合②
- $M<N$の行列<br>
$\left(\begin{array}{cc} 1 & 1 & -3 \\ -1 & 3 & 5\\ \end{array} \right) \to \left(\begin{array}{cc} 1 & 1 & -3 \\ 0 & 2 & 1 \\ \end{array} \right) $<br>$\Longleftrightarrow rank=2\neq N \Longleftrightarrow $線形従属<br>
<br>
予期される出力はTrue

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- タイトルの修正
- ↔︎の修正
- ・はない方が無難

In [0]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1,1,-3],[-1,0,5]],dtype="float64")
        actual = linearly_independent(A)
        self.assertFalse(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK


## 2.1 $M\times N$行列の列ベクトルが線形従属の場合③
- $3\times 3$，$2\times 3$の場合においてfloat型，Complex型についても調べた．
- $2\times 2$，$3\times 4$についても同様に調べた．

$\Rightarrow$ すべてのパターンにおいて結果が一致した．

### <font color="DarkOrange"> 上のセルに対するコメント</font>
- タイトルの修正
- floatは全部小文字なのにComplexは大文字スタートなのは，Complexは自作のクラスだから？\
  意味を持たせているならスルーでOK

## まとめ
- jupyter notebookの使い方を理解できた．
- unittestの使い方を理解できた．
- 線形独立と線形従属について，さらにランクとの関係性についても理解を深めることができた．
- 本の内容を理解することで，信号処理に必要な数学を知ることができた．


In [0]:
%%HTML
<link rel="stylesheet" type="text/css" href="SEMIcustom.css">

In [0]:
import unittest
import numpy as np
from linearly_check import linearly_independent
from column_space import column_space

ModuleNotFoundError: No module named 'column_space'

### <font color="DarkOrange"> 上のセルに対するコメント</font>
何故こいつをここに？\
念のためだけど発表しながら実行できた方がいいと思うよ．\
（最初に実行してからスライド再生するならいいと思う）

In [0]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1j],[2]])
        B=np.array([[1+1j,4j],[-3-3j,-12j]])
        actual = column_space(A,B,1)
        self.assertFalse(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

In [0]:
#RISEのインストール
!pip install RISE
!jupyter-nbextension install rise --py --sys-prefix
!jupyter-nbextension enable rise --py --sys-prefix