# B4 本読み第 4 回 
## 基底と部分空間<br>
 テスト担当：大畑 昌輝，実装担当：伊藤 秀真

# 目次
- jupyter notebook
- 目的
- テスト環境
- 実装課題
- 線形独立と線形従属
- 課題の仕様とテスト結果
- まとめ

# jupyter notebook
- コード，および説明テキストを含むドキュメントを作成<br>および共有できるオープンソースのWebアプリケーション
- 対応している言語はPythonの他にも40種類以上
- RISEというアドオンを使うことでスライドを作ることもできる．


# 目的
- jupyter notebookの使い方を理解する．
- 本の内容を理解する．
- 指定された実装課題を様々なパターンでテストする．

# テスト環境
- OS:Windows10 Home
- コードの開発環境:jupyter notebook(Python3.7.4)

# 実装課題
- $M\times 1$ の列ベクトルが，$M\times N$ 行列の列空間に含まれるか判定する関数を実装
- $M\times N$ 行列の列ベクトルが線型独立かどうか判定する関数を実装

## 線形独立と線形従属
ベクトル空間 $V$ の $N$ 個の要素 $u_1,u_2,\dots,u_N\in{V}$，<br>スカラ $c_i,i=1,\dots,N$ に対して，<br><br>
$c_1u_1+c_2u_2+\dots+c_Nu_N= 0$ <br><br>
となる必要十分条件が $c_1=c_2=\dots c_N=0$ であるとき，$u_1,u_2,\dots,u_N$ は線形独立といい，そうでない場合は一次従属であると言う．
    

## 1. $A\in{\mathbb{C}^{M \times 1}}$ が$M\times N$行列の列空間に含まれるか判定する関数の仕様①

- ランク $\Longleftrightarrow$ 線形独立な列ベクトル又は行ベクトルの最大本数
- $A$ が$M\times N$ 行列の列空間に含まれる $\Longleftrightarrow$ $M \times N$行列の<br>線形独立な列ベクトルの個数$\ge$$A$の 0 でない要素の数
<br><br>
以上の2点から，$M\times N$行列を$B$ とすると $Rank(B)\ge A$の<br>非零の要素数の時，行列$A$ は$M\times N$ の列空間に含まれる．



## 1. $A\in{\mathbb{C}^{M \times 1}}$ が$M\times N$行列の列空間に含まれるか判定する関数の仕様②
### 実装手順
- 与えられた$M\times N$行列の行基本変形を繰り返し，階段行列を作る．
- 階段行列のすべて 0 でない行の数をカウントし，ランクを求める．
- そのランクが$A$ の非零の要素数以上の場合，True を返し，それ以外は False を返す．

### 1.1 テストケース①<br>（正方行列，列空間に含まれる場合）
$M=N=3$ の正方行列<br>
以降，$\mathbb{C}^{M \times 1}$に属する行列を $A$，$M\times N$行列を $B$ とする．<br>
$A=\left(\begin{array}{cc} 1 \\ 1 \\ -3 \\ \end{array} \right) ,B= \left(\begin{array}{cc} 1 & 1 & -3 \\ -1 & 3 & 5 \\ 0 & 3 & 6 \\ \end{array} \right)$<br><br>$　 \Longrightarrow　rank(B)=$$A$ の非零の要素数 =3
<br><br>
予期される出力は True

In [15]:
import unittest
import numpy as np
from culumn_space import column_space

In [16]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1],[1],[-3]])
        B=np.array([[1,1,-3],[-1,3,5],[0,3,6]],dtype="float64")
        actual = column_space(A,B,1)
        self.assertTrue(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.

[[ 1.  1. -3.]
 [ 0.  4.  2.]
 [ 0.  3.  6.]]
→
[[ 1.  1. -3.]
 [ 0.  4.  2.]
 [ 0.  3.  6.]]
→
[[ 1.   1.  -3. ]
 [ 0.   4.   2. ]
 [ 0.   0.   4.5]]
→



----------------------------------------------------------------------
Ran 1 test in 0.002s

OK


### 1.1 テストケース②（横長行列，列空間に含まれる場合）
$M=3，N=4$ の行列<br>
<br>
$A=\left(\begin{array}{cc} 0 \\ 1 \\ 0 \\ \end{array} \right) ,B= \left(\begin{array}{cc} 1 & 2 & -3 & 5 \\ 0 & 3 & -3 & 8 \\ 2 & 4 & -6 & 10 \\ \end{array} \right)$　<br><br>　$\Longrightarrow rank(B)=2 \ge$$A$ の非零の要素数 =1
<br><br>
予期される出力は True

In [4]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[0],[1],[0]])
        B=np.array([[1,2,-3,5],[0,3,-3,8],[2,4,-6,10]],dtype="float64")
        actual = column_space(A,B,1)
        self.assertTrue(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.

[[ 1.  2. -3.  5.]
 [ 0.  3. -3.  8.]
 [ 2.  4. -6. 10.]]
→
[[ 1.  2. -3.  5.]
 [ 0.  3. -3.  8.]
 [ 0.  0.  0.  0.]]
→
[[ 1.  2. -3.  5.]
 [ 0.  3. -3.  8.]
 [ 0.  0.  0.  0.]]
→



----------------------------------------------------------------------
Ran 1 test in 0.007s

OK


### 1.1 テストケース③（その他，列空間に含まれる場合）
- $3\times 2$，$3\times 3$，$3\times 4$ の場合において float 型，complex 型についても調べた．
- $4\times 3$，$4\times 4$，$4\times 5$ の場合についても同様に調べた．

$\Rightarrow$ すべてのパターンにおいて結果が一致した．

### 1.2 テストケース①（正方行列，列空間に含まれない場合）
$M=N=3$ の正方行列<br>
<br>
$A=\left(\begin{array}{cc} 1 \\ 1 \\ -3 \\ \end{array} \right) ,B= \left(\begin{array}{cc} 1 & 1 & -3 \\ -1 & 3 & 5 \\ 3 & 3 & -9 \\ \end{array} \right) $<br><br>$　\Longrightarrow rank(B) =2 <$$A$ の非零の要素数 =3
<br><br>
予期される出力は False

In [5]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1],[1],[-3]])
        B=np.array([[1,1,-3],[-1,3,5],[3,3,-9]],dtype="float64")
        actual = column_space(A,B,1)
        self.assertFalse(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.

[[ 1.  1. -3.]
 [ 0.  4.  2.]
 [ 3.  3. -9.]]
→
[[ 1.  1. -3.]
 [ 0.  4.  2.]
 [ 0.  0.  0.]]
→
[[ 1.  1. -3.]
 [ 0.  4.  2.]
 [ 0.  0.  0.]]
→



----------------------------------------------------------------------
Ran 1 test in 0.005s

OK


### 1.2 テストケース②（縦長行列，列空間に含まれない場合）
$M=4，N=3$ の行列<br>
<br>
$A=\left(\begin{array}{cc} 1 \\ 1 \\ -3 \\ 2 \\\end{array} \right) ,B= \left(\begin{array}{cc} 1 & 1 & -3 \\ -1 & 3 & 5\\ 5 & 7 & -3 \\ 3 & 3 & -9 \\ \end{array} \right)$<br><br>$　\Longrightarrow　rank(B)=$3$<$$A$ の非零の要素数 $=4$
<br><br>
予期される出力は False

In [6]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1],[1],[-3],[2]])
        B=np.array([[1,1,-3],[-1,3,5],[5,7,-3],[3,3,-9]],dtype="float64")
        actual = column_space(A,B)
        self.assertFalse(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK


### 1.2 テストケース③（その他の列空間に含まれない場合）
- $3\times 2$，$3\times 3$，$3\times 4$ の場合において float 型，complex 型についても調べた．
- $4\times 3$, $4\times 4$，$4\times 5$ の場合についても同様に調べた．

$\Rightarrow$ すべてのパターンにおいて結果が一致した．

### 2.$M\times N$ の行列の列ベクトルが線型独立かどうか判定する関数の仕様
ランクは 1 次独立な列ベクトルの最大本数であるため，
$A\in{\mathbb{C}^{M \times N}}$ について，$Rank(A)=N$ であるとき，$A$の列ベクトルはすべて線形独立である．
### 実装手順
- 入力行列の行数と列数をチェックし，$M<N$の時ランクが$N$にならないため False を返す．
- 与えられた行列の行基本変形を繰り返し，階段行列を作る．
- 階段行列のすべて 0 でない行の数をカウントしランクを求める．
- $Rank(A)=N$の場合は True，異なる場合は False を返す．

### 2.1 テストケース①（正方行列，線形独立の場合）
$M=N=3$ の正方行列<br>
$\left(\begin{array}{cc} 1 & 1 & -3 \\ -1 & 3 & 5 \\ 0 & 3 & 6\\ \end{array} \right) \to \left(\begin{array}{cc} 1 & 1 & -3 \\ 0 & 2 & 1 \\ 0 & 0 & \frac{9}{2} \\ \end{array} \right) $<br>$\Longrightarrow rank=N=3 \Longleftrightarrow $線形独立 <br>
<br>
予期される出力は True

In [8]:
from linearly_check import linearly_independent

In [9]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1,1,-3],[-1,3,5],[0,3,6]],dtype="float64")
        actual = linearly_independent(A)
        self.assertTrue(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.

[[ 1.  1. -3.]
 [-1.  3.  5.]
 [ 0.  3.  6.]]
→
[[ 1.  1. -3.]
 [ 0.  4.  2.]
 [ 0.  3.  6.]]
→
[[ 1.  1. -3.]
 [ 0.  4.  2.]
 [ 0.  3.  6.]]
→
[[ 1.   1.  -3. ]
 [ 0.   4.   2. ]
 [ 0.   0.   4.5]]
→



----------------------------------------------------------------------
Ran 1 test in 0.006s

OK


### 2.1 テストケース②（縦長行列，線形独立の場合）
$M>N$の行列<br>
$\left(\begin{array}{cc} 1 & 1 \\ -1 & 3 \\ 0 & 3 \\ \end{array} \right) \to \left(\begin{array}{cc} 1 & 1 \\ 0 & 4 \\ 0 & 0 \\ \end{array} \right) $<br>$\Longrightarrow rank=N=2 \Longleftrightarrow $線形独立 <br>
<br>
予期される出力は True

In [10]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1,1],[-1,3],[0,3]],dtype="float64")
        actual = linearly_independent(A)
        self.assertTrue(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.

[[ 1.  1.]
 [-1.  3.]
 [ 0.  3.]]
→
[[1. 1.]
 [0. 4.]
 [0. 3.]]
→
[[1. 1.]
 [0. 4.]
 [0. 3.]]
→
[[1. 1.]
 [0. 4.]
 [0. 0.]]
→



----------------------------------------------------------------------
Ran 1 test in 0.006s

OK


### 2.1 テストケース③（その他，線形独立の場合）
- $3\times 3$，$3\times 2$の場合において float 型，complex 型についても調べた．
- $2\times 2$，$4\times 3$についても同様に調べた．

$\Rightarrow$ すべてのパターンにおいて結果が一致した．

### 2.2 テストケース①（正方行列，線形従属の場合）
$M=N$の正方行列<br>
$\left(\begin{array}{cc} 1 & 1 & -3 \\ -1 & 0 & 5 \\ 0 & 3 & 6\\ \end{array} \right) \to \left(\begin{array}{cc} 1 & 1 & -3 \\ 0 & 1 & 2 \\ 0 & 0 & 0\\ \end{array} \right) $<br>$\Longrightarrow rank=2\neq N \Longrightarrow $線形従属<br>
<br>
予期される出力は False

In [11]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1,1,-3],[-1,0,5],[0,3,6]],dtype="float64")
        actual = linearly_independent(A)
        self.assertFalse(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.

[[ 1.  1. -3.]
 [-1.  0.  5.]
 [ 0.  3.  6.]]
→
[[ 1.  1. -3.]
 [ 0.  1.  2.]
 [ 0.  3.  6.]]
→
[[ 1.  1. -3.]
 [ 0.  1.  2.]
 [ 0.  3.  6.]]
→
[[ 1.  1. -3.]
 [ 0.  1.  2.]
 [ 0.  0.  0.]]
→



----------------------------------------------------------------------
Ran 1 test in 0.007s

OK


### 2.2 テストケース②（横長行列，線形従属の場合）
$M<N$の行列<br>
$\left(\begin{array}{cc} 1 & 1 & -3 \\ -1 & 3 & 5\\ \end{array} \right) \to \left(\begin{array}{cc} 1 & 1 & -3 \\ 0 & 2 & 1 \\ \end{array} \right) $<br>$\Longrightarrow rank=2\neq N \Longrightarrow $線形従属<br>
<br>
予期される出力は False

In [12]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1,1,-3],[-1,0,5]],dtype="float64")
        actual = linearly_independent(A)
        self.assertFalse(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK


### 2.2 テストケース③（その他，線形従属の場合）
- $3\times 3$，$2\times 3$の場合において float 型，complex 型についても調べた．
- $2\times 2$，$3\times 4$についても同様に調べた．

$\Rightarrow$ すべてのパターンにおいて結果が一致した．

## まとめ
- jupyter notebookの使い方を理解できた．
- unittestの使い方を理解できた．
- 線形独立と線形従属について，さらにランクとの関係性についても理解を深めることができた．
- 本の内容を理解することで，信号処理に必要な数学を知ることができた．


### 付録 テストケース（複素数の正方行列，列空間に含まれない場合）
$M=N=2$ の正方行列<br>
<br>
$A=\left(\begin{array}{cc} j \\ 2 \\ \end{array} \right) ,B= \left(\begin{array}{cc} 1+j & 4j  \\ -3-3j & -12j \\ \end{array} \right) $<br><br>$　\Longrightarrow rank(B) =1 <$$A$ の非零の要素数 =2
<br><br>
予期される出力は False

In [14]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[1j],[2]])
        B=np.array([[1+1j,4j],[-3-3j,-12j]])
        actual = column_space(A,B,1)
        self.assertFalse(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.

[[1.+1.j 0.+4.j]
 [0.+0.j 0.+0.j]]
→



----------------------------------------------------------------------
Ran 1 test in 0.047s

OK


### 付録 行基本変形のテスト
$M=N=3$ の正方行列<br>
$\left(\begin{array}{cc} 0 & 3 & 6 \\ 1 & 1 & -3 \\ -1 & 3 & 5\\ \end{array} \right) $<br>$\Longrightarrow rank=N=3 \Longleftrightarrow $線形独立 <br>
<br>
予期される出力は True

In [ ]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[0,3,6],[1,1,-3],[-1,3,5]],dtype="float64")
        actual = linearly_independent(A)
        self.assertTrue(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

### 付録 行基本変形のテスト
$M=N=3$ の正方行列<br>
$\left(\begin{array}{cc} 0 & 3 & 6 \\ 0& 1 & -3 \\ 0 & 3 & 5\\ \end{array} \right) $

In [13]:
class Testlinearly(unittest.TestCase):
    def test_linearly(self):
        A=np.array([[0,3,6],[0,2,-2],[0,5,7]],dtype="float64")
        actual = linearly_independent(A)
        self.assertFalse(actual)
        
if __name__ == '__main__': unittest.main(argv=['first-arg-is-ignored'], exit=False)

.

[[ 0.  3.  6.]
 [ 0.  2. -2.]
 [ 0.  5.  7.]]
→
[[ 0.  3.  6.]
 [ 0.  0. -6.]
 [ 0.  5.  7.]]
→
[[ 0.  3.  6.]
 [ 0.  0.  0.]
 [ 0.  0. -6.]]
→



----------------------------------------------------------------------
Ran 1 test in 0.005s

OK


In [7]:
%%HTML
<link rel="stylesheet" type="text/css" href="SEMIcustom.css"

In [ ]:
#RISEのインストール
!pip install RISE
!jupyter-nbextension install rise --py --sys-prefix
!jupyter-nbextension enable rise --py --sys-prefix