In [21]:
import numpy as np
from ch8_ver7 import sample_mean, sample_variance, sample_covariance_matrix, whitening_matrix
def white(mat):
    X = np.array(mat)
    gyou = X.shape[0]
    retu = X.shape[1]
    C = np.cov(X, bias=True)
    lam, U = np.linalg.eig(C)
    t = np.array([ -1 if i == True else 1 for i in U[0]<0 ])
    U = U * t
    indx = lam.argsort()[::-1]
    lam = lam[indx]
    U = U[:,indx]
    print("matsu")
    print(U)
    Lam = np.diag(lam)
    res = np.dot(np.linalg.inv(np.sqrt(Lam)),U.T)
    return res

In [22]:
a = np.array([[40, 80, 90], [80, 90, 100]])
b = np.array([[-45.82,-25.35,-32.05,39.32], [28.12,-14.17,33.94,-22.47], [-43.96,37.21,2.99,21.92]])
c = np.array([[-1,4.3,-1.1,-0.7,-1],[-5.6,-8,-3.2,3.4,-1.6],[7,-3.6,-2,-2.6,0.4],[-3.1,-1.1,4,5.6,1.7]])

In [23]:
aw = white(a)
bw = white(b)
cw = white(c)
aws = whitening_matrix(a)
bws = whitening_matrix(b)
cws = whitening_matrix(c)

matsu
[[ 0.94027158  0.34042526]
 [ 0.34042526 -0.94027158]]
matsu
[[ 0.64342385  0.67708876  0.35715061]
 [-0.51097587  0.03247482  0.8589814 ]
 [ 0.57000825 -0.73518446  0.36687109]]
matsu
[[ 0.122864    0.47947366  0.62888431  0.59959484]
 [-0.64031768 -0.45324281  0.60412579 -0.13998661]
 [ 0.4684126  -0.75143402  0.03999134  0.46296571]
 [-0.59622759 -0.00478294 -0.48778812  0.63761472]]


In [28]:
exp = np.array([[0.023342910587869133, -0.12165384962747014, 0.08899363123730368, -0.1132771806067438], [0.12387241888532186, -0.11709565785890363, -0.1941336043291668, -0.0012356773195523584], [0.5338130178481921, 0.5127973559490143, 0.03394566591585277, -0.41404698243612936], [2.7978562593515828, -0.6532117590551376, 2.1603112740043433, 2.975266304140435]])
np.array(exp).shape

(4, 4)

In [4]:
from itertools import product
# for i, j in product(range(len(exp)), repeat=2):
#     print(i,j)
list(product(range(4), repeat=2))

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3)]