In [2]:
import numpy as np

def whitening(x):
    X = np.array(x)
    d = X.shape[0]
    n = X.shape[1]
    mu = X.mean(axis = 1).reshape((d, 1))
    C = np.dot((X - mu), (X - mu).T) / n
    lam, U = np.linalg.eig(C)
    LAMBDA = np.diag(lam)
    res = np.dot(np.linalg.inv(np.sqrt(LAMBDA)), U.T)
#     res = np.dot(np.linalg.inv(np.sqrt(LAMBDA)), np.dot(U.T, X))
    return res

In [3]:
fl=[[-45.82,-25.35,-32.05,39.32], [28.12,-14.17,33.94,-22.47], [-43.96,37.21,2.99,21.92]]
fl_res = whitening(fl)
print(fl_res)

[[-0.01424567  0.01131322 -0.01262022]
 [ 0.03135495  0.00150386 -0.03404527]
 [ 0.03259725  0.0783995   0.03348444]]


In [4]:
flint = [[-1,4.3,-1.1,-0.7,-1],[-5.6,-8,-3.2,3.4,-1.6],[7,-3.6,-2,-2.6,0.4],[-3.1,-1.1,4,5.6,1.7]]
flint_res = whitening(flint)
print(flint_res)

[[ 2.33429106e-02 -1.21653850e-01  8.89936312e-02 -1.13277181e-01]
 [ 1.23872419e-01 -1.17095658e-01 -1.94133604e-01 -1.23567732e-03]
 [-2.79785626e+00  6.53211759e-01 -2.16031127e+00 -2.97526630e+00]
 [-5.33813018e-01 -5.12797356e-01 -3.39456659e-02  4.14046982e-01]]


In [18]:
X = np.array(flint)
d = X.shape[0]
n = X.shape[1]
mu = X.mean(axis = 1).reshape((d, 1))
C = np.dot((X - mu), (X - mu).T) / n
lam, U = np.linalg.eig(C)
print(lam)
print(U)
lam = np.sort(lam)[::-1]
U = U[:, [0,1,3,2]]
print(lam)
print(U)
LAMBDA = np.diag(lam)
res = np.dot(np.linalg.inv(np.sqrt(LAMBDA)), U.T)

[27.70379583 14.98236146  0.04592667  1.38791604]
[[ 0.122864    0.47947366 -0.59959484 -0.62888431]
 [-0.64031768 -0.45324281  0.13998661 -0.60412579]
 [ 0.4684126  -0.75143402 -0.46296571 -0.03999134]
 [-0.59622759 -0.00478294 -0.63761472  0.48778812]]
[27.70379583 14.98236146  1.38791604  0.04592667]
[[ 0.122864    0.47947366 -0.62888431 -0.59959484]
 [-0.64031768 -0.45324281 -0.60412579  0.13998661]
 [ 0.4684126  -0.75143402 -0.03999134 -0.46296571]
 [-0.59622759 -0.00478294  0.48778812 -0.63761472]]


In [19]:
print(res)

[[ 2.33429106e-02 -1.21653850e-01  8.89936312e-02 -1.13277181e-01]
 [ 1.23872419e-01 -1.17095658e-01 -1.94133604e-01 -1.23567732e-03]
 [-5.33813018e-01 -5.12797356e-01 -3.39456659e-02  4.14046982e-01]
 [-2.79785626e+00  6.53211759e-01 -2.16031127e+00 -2.97526630e+00]]
